<form action="LOGINPDO1.PHP" method="post">
<p class="text-white-50 mb-5">Please enter your login and password!</p>

<div class="form-outline form-white mb-4">
  <input type="text" name="PNO" id="typeEmailX" class="form-control form-control-lg" />
  <label class="form-label" for="typeEmailX">PHONENO</label>
</div>

<div class="form-outline form-white mb-4">
  <input type="password" name="PASS" id="typePasswordX" class="form-control form-control-lg" />
  <label class="form-label" for="typePasswordX">PASSWORD</label>
</div>

<p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot password?</a></p>

<button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
</form>t 